version: "3"

services:
  admin:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=server
    ports:
      - "8080:80"
  product:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=client
    ports:
      - "3000:80"
